"""Build src/data/elements.js from Bowserinator's Periodic-Table-JSON (CC BY-SA).
Source: https://github.com/Bowserinator/Periodic-Table-JSON
Run: python3 tools/gen_elements.py
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
raw = json.load(open(os.path.join(HERE, "PeriodicTableJSON.json")))["elements"]

def cat(c):
    if "unknown" in c: return "unknown"
    if c in ("diatomic nonmetal", "polyatomic nonmetal"): return "reactive nonmetal"
    return c

out = []
for e in raw:
    if e["number"] > 118: continue
    img = e.get("image") or {}
    out.append({
        "n": e["number"], "sym": e["symbol"], "name": e["name"],
        "mass": e["atomic_mass"], "cat": cat(e["category"]), "rawCat": e["category"],
        "x": e["xpos"], "y": e["ypos"], "group": e.get("group"), "period": e["period"],
        "block": e.get("block"), "phase": e.get("phase"),
        "melt": e.get("melt"), "boil": e.get("boil"), "density": e.get("density"),
        "en": e.get("electronegativity_pauling"), "ea": e.get("electron_affinity"),
        "ie": (e.get("ionization_energies") or [None])[0] if e.get("ionization_energies") else None,
        "molarHeat": e.get("molar_heat"),
        "config": e.get("electron_configuration"), "configS": e.get("electron_configuration_semantic"),
        "shells": e.get("shells"), "appearance": e.get("appearance"),
        "discoveredBy": e.get("discovered_by"), "namedBy": e.get("named_by"),
        "summary": e.get("summary"), "wiki": e["source"].rsplit("/", 1)[-1],
        "cpk": e.get("cpk-hex"),
        "img": {"url": img.get("url"), "title": img.get("title"), "credit": img.get("attribution")},
        "glb": e.get("bohr_model_3d"),
    })

path = os.path.join(HERE, "..", "src", "data", "elements.js")
with open(path, "w") as f:
    f.write("// Generated by tools/gen_elements.py from Bowserinator/Periodic-Table-JSON (CC BY-SA 3.0).\n")
    f.write("export const ELEMENTS = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n")
print(len(out), "elements written")
