"""Build src/data/nuclides.js.
Masses + natural abundances: all-isotopes npm package (MIT, AME/IUPAC values).
Half-lives, decay modes, progeny: radioactivedecay python package (ICRP-107 dataset).
Run: pip install radioactivedecay && python3 tools/gen_nuclides.py
"""
import json, math, os
import radioactivedecay as rd

HERE = os.path.dirname(os.path.abspath(__file__))
iso = json.load(open(os.path.join(HERE, "allIsotopes.json")))
rdset = set(str(x) for x in rd.DEFAULTDATA.nuclides)

# Longest-lived known isotopes of superheavy elements (not in ICRP-107), seconds (approximate literature values).
SUPERHEAVY = {
    "Md-258": 51.5*86400, "Md-260": 27.8*86400, "No-259": 58*60, "Lr-266": 11*3600, "Rf-267": 1.3*3600,
    "Db-268": 16*3600, "Sg-269": 14*60, "Bh-270": 61, "Hs-269": 16, "Mt-278": 4.5, "Ds-281": 12.7,
    "Rg-282": 100, "Cn-285": 30, "Nh-286": 9.5, "Fl-289": 1.9, "Mc-290": 0.65, "Lv-293": 0.057,
    "Ts-294": 0.051, "Og-294": 0.0007,
}
SH_MODE = {"Md-258": ["α"], "Md-260": ["SF"], "No-259": ["α", "EC"], "Lr-266": ["SF"], "Rf-267": ["SF"],
    "Db-268": ["SF", "EC"], "Sg-269": ["α"], "Bh-270": ["α"], "Hs-269": ["α"], "Mt-278": ["α"], "Ds-281": ["SF", "α"],
    "Rg-282": ["α"], "Cn-285": ["α"], "Nh-286": ["α"], "Fl-289": ["α"], "Mc-290": ["α"], "Lv-293": ["α"],
    "Ts-294": ["α"], "Og-294": ["α"]}

out = []
for el in iso:
    Z = el["atomic_number"]
    for i in el["isotopes"]:
        name = i["nuclide"]; A = i["mass_number"]
        rec = {"z": Z, "a": A, "m": i["mass"], "ab": i["abundance"] or 0}
        if name in rdset:
            n = rd.Nuclide(name)
            hl = n.half_life("s")
            if math.isinf(hl):
                rec["hl"] = -1
            else:
                rec["hl"] = float("%.5g" % hl)
                rec["dm"] = list(n.decay_modes())
                rec["pr"] = list(n.progeny())
                rec["bf"] = [float("%.4g" % b) for b in n.branching_fractions()]
        elif name in SUPERHEAVY:
            rec["hl"] = SUPERHEAVY[name]; rec["dm"] = SH_MODE[name]; rec["pr"] = []; rec["bf"] = []
        elif rec["ab"] > 0:
            rec["hl"] = -1
        out.append(rec)
        # metastable states that ICRP lists (e.g. Tc-99m)
        if name + "m" in rdset:
            n = rd.Nuclide(name + "m")
            out.append({"z": Z, "a": A, "iso": "m", "m": i["mass"], "ab": 0,
                        "hl": float("%.5g" % n.half_life("s")), "dm": list(n.decay_modes()),
                        "pr": list(n.progeny()), "bf": [float("%.4g" % b) for b in n.branching_fractions()]})

path = os.path.join(HERE, "..", "src", "data", "nuclides.js")
with open(path, "w") as f:
    f.write("// Generated by tools/gen_nuclides.py. Masses/abundances: all-isotopes (MIT). Half-lives & decay: ICRP-107 via radioactivedecay.\n")
    f.write("// hl: half-life in seconds, -1 = stable, missing = short-lived/unmeasured in dataset.\n")
    f.write("export const NUCLIDES = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n")
print(len(out), "nuclides;", sum(1 for r in out if r.get("hl") == -1), "stable;", sum(1 for r in out if r.get("hl", -1) > 0), "with half-life")
